export const DATA_LOADING = "DATA_LOADING";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const API_ERROR = "API_ERROR";

export const VEHICLES_LOADING = "VEHICLES_LOADING";
export const VEHICLES_SUCCESS = "VEHICLES_SUCCESS";
export const VEHICLES_ERROR = "VEHICLES_ERROR";

export const FILMS_LOADING = "FILMS_LOADING";
export const FILMS_SUCCESS = "FILMS_SUCCESS";
export const FILMS_ERROR = "FILMS_ERROR";

export const SPECIES_LOADING = "SPECIES_LOADING";
export const SPECIES_SUCCESS = "SPECIES_SUCCESS";
export const SPECIES_ERROR = "SPECIES_ERROR";

export const STARSHIPS_LOADING = "STARSHIPS_LOADING";
export const STARSHIPS_SUCCESS = "STARSHIPS_SUCCESS";
export const STARSHIPS_ERROR = "STARSHIPS_ERROR";

export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
